CC = gcc

SUBDIR = node location pesanan point to_do_list in_progress_list tas wordmachine utilities 
SRCS = $(wildcard *.c $(foreach fd, $(SUBDIR), $(fd)/*.c))

output: $(SRCS)
	$(CC) $(SRCS) -o output